### PR TITLE
Fixed getValue for Checkbox. Updated README for how to retrieve check…

### PR DESCRIPTION
**Pull request by joshuamanns**
Please accept this PR to get Checkbox functioning properly. See issue #56

### CODE REVIEW

**Comment by SeeThruHead** [comment]
Can you go into a little more detail behind the motivation for this change? None of the other inputs have a defaults prop as defaults are handled by defaultValues on the form itself.

**Comment by joshuamanns** [comment]
@SeeThruHead The current implementation seems to have a conflict where defaultValue is respected for initial state, but does not allow the Checkbox to be a controlled component. You can see it in origin/master stories/Checkbox.js - at least on Chrome latest, checkboxes are not functioning.

**Comment by tannerlinsley** [comment]
Please don't commit `lib/` or other dist files :)

**Comment by SeeThruHead** [comment]
Am I correct in thinking you cannot make any of the shipped inputs "controlled"? I think that is the case. Do you have a concrete use-case that you're trying to meet? I think there's likely a way to do what you want without this PR, but I would need to know more about your use-case to advise.

**Comment by tannerlinsley** [comment]
`/lib` files are still present in the PR

**Comment by tannerlinsley** [comment]
This is fixed in the latest version.  `defaultValues` is now used to determine if a Checkbox is checked by default now.

**Pull request closed without merging**
