### PR TITLE
Allow noTouch to be customizable / Document

### PR DESCRIPTION
**Pull request by chibicode**
I wanted to be able to modify `noTouch` values for each input so that validation only runs on blur. Also added documentation about `noTouch` on README.

### CODE REVIEW

**Comment by chibicode** [comment]
Regardless of this being merged or not, a version bump would be appreciated to bring in changes like https://github.com/tannerlinsley/react-form/pull/11.

**Comment by tannerlinsley** [comment]
Nice addition!

**Comment by tannerlinsley** [comment]
Just cut a release with these features: https://github.com/tannerlinsley/react-form/releases/tag/v0.11.0

**Comment by chibicode** [comment]
@tannerlinsley thanks!

**Pull request merged**
